default_settings: null
behaviors:
  Combat Behavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 131072
      learning_rate: 0.0003
      beta: 0.02
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      shared_critic: false
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    checkpoint_interval: 500000
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          memory: null
          goal_conditioning_type: hyper
          deterministic: false
    init_path: null
    keep_checkpoints: 5
    even_checkpoints: false
    max_steps: 5000000
    time_horizon: 512
    summary_freq: 50000
    threaded: false
    self_play: null
    behavioral_cloning: null
      # demo_path: Assets/Demonstrations/MonsterDemonstrations
      # strength: 0.5
      # steps: 500000
      # batch_size: 1024
      # samples_per_update: 8192
      # num_epoch: 3
env_settings:
  env_path: null
  env_args: null
  base_port: 5005
  num_envs: 1
  num_areas: 10
  timeout_wait: 7200
  seed: -1
engine_settings:
  width: 84
  height: 84
  quality_level: 5
  time_scale: 20
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: false
  no_graphics_monitor: false
environment_parameters: null
checkpoint_settings:
  run_id: multiCombatAgent2_NewBT_202AS_D_1024BA_131072BU_PartialDefeatCred_NoVar_BC_500K_05S_8192SPU
  initialize_from: null
  load_model: false
  resume: true
  force: false
  train_model: true
  inference: false
  results_dir: results
torch_settings:
  device: null
debug: false